### ISSUE TITLE
Tests fail because Jest doesn't close down the server correctly at the end of the test run

### ISSUE THREAD

**Issue by TheWoodenMan** [TheWoodenMan/behavioural-recruitment#24]
Tests fail because Jest doesn't close down the server correctly at the end of the test run

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPSERVERWRAP

      32 | app.use("/api", apiRoutes);
      33 |
    > 34 | const server = app.listen(process.env.PORT || 3000, () => {
         |                    ^
      35 |      console.log(`Your server is listening on port ${process.env.PORT || 3000}`);
      36 | });
      37 |

      at Function.listen (node_modules/express/lib/application.js:635:24)
      at Object.listen (server.js:34:20)
      at Object.require (server.test.js:2:13)
```

related research:

https://stackoverflow.com/questions/50818367/how-to-fix-err-jest-has-detected-the-following-3-open-handles-potentially-keepin
https://stackoverflow.com/questions/14515954/how-to-properly-close-node-express-server

**Comment by TheWoodenMan** [comment]
https://stackoverflow.com/questions/68437734/jest-has-detected-the-following-1-open-handle-potentially-keeping-jest-from-exit

recommends removing detectOpenHandles from jest config - it seems to have worked but don't think it is the most 100% elegant solution.
